api_version = 1
id = "org.mochios.msh"
name = "mochi shell"
version = "0.1.0"
entry = "/bin/msh"
role = "application"

[capabilities]
requires = [
    "fs.read.all",
    "ipc.server",
    "process.spawn",
]
