[package]
name = "msh"
version = "0.1.0"
edition = "2024"

[workspace]

[dependencies]
libc = { git = "https://github.com/mochiOS/libc", package = "libc" }
mochi-user-syscall = { git = "https://github.com/mochiOS/syscalls", package = "mochi-user-syscall" }
mochios-capability-protocol = { git = "https://github.com/mochiOS/syscalls", package = "mochios-capability-protocol" }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
