[package]
id = "org.mochios.msh"
name = "mochi shell"
version = "0.1.0"
vendor = "mochiOS Project"

[[binary]]
path = "/bin/msh"
kind = "application"
requires = [
    "fs.read.all",
    "ipc.client",
    "ipc.server",
    "process.spawn",
]
